# 端口
server:
  port: 8081
# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

# mybatis-plus设置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml